---
name: "TestSuite"

on:
  push

jobs:
  analyze:
    name: TestSuite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      # Build picotls and picoquic.
      - name: Install picotls
        run: |
          sudo apt-get install -y libssl-dev
          ls -l ./ci
          ./ci/build_picotls.sh
      - name: Install picoquic
        run: |
          ./ci/build_picoquic.sh
      - name: Install picoquic_ns
        run: |
          ./ci/build_picoquic_ns.sh
     
